In [157]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [158]:
df2=pd.read_csv('detect_dataset.csv')


In [159]:
x=df2.iloc[:,1:7].values
y=df2.iloc[:,0].values

In [160]:
x[0]

array([-1.70472196e+02,  9.21961350e+00,  1.61252583e+02,  5.44900040e-02,
       -6.59920931e-01,  6.05430928e-01])

In [161]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest=train_test_split(x,y,test_size=.2,random_state=0)
xtrain

array([[ 1.55020034e+02, -8.31068761e+02,  6.76046464e+02,
        -3.35177620e-02, -5.66553800e-03,  3.91833000e-02],
       [ 5.79455017e+01, -7.21415453e+00, -4.87913724e+01,
         1.64504505e-01,  4.30608427e-01, -5.95112932e-01],
       [-7.21360596e+01,  6.25513165e+01,  6.23285087e+00,
        -9.71541030e-02, -4.57479539e-01,  5.54633642e-01],
       ...,
       [ 1.61716572e+01,  7.47688582e+01, -9.41911487e+01,
        -5.06501418e-01,  5.74454786e-01, -6.79533680e-02],
       [-6.59598120e+01,  3.91559313e+01,  2.35855152e+01,
         1.20924870e-01, -5.58918725e-01,  4.37993855e-01],
       [ 8.66389530e+02, -5.46708868e+02,  6.45281515e+00,
         1.50904790e-02, -2.63440956e-01,  2.48350477e-01]])

In [162]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
xtrain=scx.fit_transform(xtrain)
xtest=scx.fit_transform(xtest)

In [163]:
ann=tf.keras.Sequential()

In [164]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [165]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [166]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [167]:
ann.compile(optimizer='adam',metrics='accuracy',loss='binary_crossentropy')

In [168]:
ann.fit(xtrain,ytrain,epochs=100,batch_size=32)

Epoch 1/100
300/300 [==============================] - 1s 1ms/step - loss: 0.5068 - accuracy: 0.8189
Epoch 2/100
300/300 [==============================] - 0s 1ms/step - loss: 0.2674 - accuracy: 0.8983
Epoch 3/100
300/300 [==============================] - 0s 1ms/step - loss: 0.1732 - accuracy: 0.9178
Epoch 4/100
300/300 [==============================] - 0s 1ms/step - loss: 0.1264 - accuracy: 0.9636
Epoch 5/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0965 - accuracy: 0.9773
Epoch 6/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0657 - accuracy: 0.9831
Epoch 7/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0521 - accuracy: 0.9852
Epoch 8/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0464 - accuracy: 0.9860
Epoch 9/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0436 - accuracy: 0.9873
Epoch 10/100
300/300 [==============================] - 0s 1ms/step - loss: 0.0411 - accura

In [169]:
pred=ann.predict(scx.transform(xtest))

In [170]:
pred=pred.reshape(1,len(pred))

In [171]:
ytest=ytest.astype('float32')

In [183]:
pred

array([[ True, False,  True, ...,  True,  True, False]])